name: Firefox Bug Handling
author: emma@mozilla.com
collections:
  policies:
    output: true
    permalink: :title
  processes:
    output: true
    permalink: :title
  guides:
    output: true
    permalink: :title
